// <auto-generated />
namespace LoteAutos2017.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ADDCOSTO_PRECIO_AUTO : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ADDCOSTO_PRECIO_AUTO));
        
        string IMigrationMetadata.Id
        {
            get { return "201703071601232_ADD-COSTO_PRECIO_AUTO"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
